version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 654654483406.dkr.ecr.ap-southeast-1.amazonaws.com/devops-test-anurak:latest
    env_file:
      - .env

